apt-get -y install ssh
apt-get -y install vim
apt-get -y install apache2
apt-get -y install apache2-doc
apt-get -y install libapache2-mod-php5
apt-get -y install autoconf
apt-get -y install automake
apt-get -y install bison
apt-get -y install ca-certificates
apt-get -y install ethtool
apt-get -y install flex
apt-get -y install g++
apt-get -y install gcc
apt-get -y install gcc-4.4
apt-get -y install libcrypt-ssleay-perl
apt-get -y install libmysqlclient-dev
apt-get -y install libnet1
apt-get -y install libnet1-dev
apt-get -y install libpcre3
apt-get -y install libpcre3-dev
apt-get -y install libphp-adodb
apt-get -y install libssl-dev
apt-get -y install libtool
apt-get -y install libwww-perl
apt-get -y install make
apt-get -y install mysql-client
apt-get -y install mysql-common
apt-get -y install mysql-server
apt-get -y install ntp
apt-get -y install php5-cli
apt-get -y install php5-gd
apt-get -y install php5-mysql
apt-get -y install php-pear
apt-get -y install sendmail-bin
apt-get -y install sendmail
apt-get -y install sysstat
apt-get -y install usbmount
apt-get -y install ibcrypt-ssleay-perl
apt-get -y install liblwp-protocol-https-perl
